"use client";

import Link from "next/link";
import { Minus, Plus, Trash2, ArrowRight } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatCurrency } from "@/lib/utils";

export default function CartPage() {
  const { items, subtotal, setQuantity, removeItem } = useCart();
  return <main className="container-shop py-12 sm:py-16"><p className="eyebrow">Your bag</p><h1 className="mt-3 text-4xl font-black tracking-tight">Shopping cart</h1>{items.length === 0 ? <div className="mt-10 rounded-[32px] bg-white p-12 text-center shadow-soft"><p className="text-lg font-bold">Your cart is empty.</p><p className="mt-2 text-sm text-neutral-500">Add something you love and it will appear here.</p><Link href="/shop" className="btn-primary mt-6">Continue shopping <ArrowRight size={16}/></Link></div> : <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="rounded-[32px] bg-white p-5 shadow-soft sm:p-7">{items.map(item => <div key={item.id} className="flex gap-4 border-b border-black/5 py-5 first:pt-0 last:border-0 last:pb-0"><img src={item.image} alt={item.name} className="h-24 w-24 rounded-2xl object-cover"/><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-wider text-neutral-400">{item.category}</p><h2 className="mt-1 truncate font-bold">{item.name}</h2><p className="mt-1 font-semibold">{formatCurrency(item.price)}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full border border-neutral-200 px-2 py-1"><button onClick={() => setQuantity(item.id, item.quantity - 1)} aria-label="Decrease"><Minus size={13}/></button><span className="w-5 text-center text-xs">{item.quantity}</span><button onClick={() => setQuantity(item.id, item.quantity + 1)} aria-label="Increase"><Plus size={13}/></button></div><button onClick={() => removeItem(item.id)} className="text-xs font-semibold text-neutral-400 hover:text-red-600"><Trash2 size={15}/></button></div></div></div>)}</div><aside className="h-fit rounded-[32px] bg-ink p-7 text-white"><p className="text-xs uppercase tracking-widest text-neutral-400">Order summary</p><div className="mt-6 flex justify-between text-sm text-neutral-300"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div><div className="mt-3 flex justify-between text-sm text-neutral-300"><span>Shipping</span><span>Calculated at checkout</span></div><div className="my-6 border-t border-white/10"/><div className="flex justify-between text-lg font-bold"><span>Total</span><span>{formatCurrency(subtotal)}</span></div><Link href="/checkout" className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-black">Proceed to checkout <ArrowRight size={16}/></Link><p className="mt-4 text-center text-[11px] text-neutral-500">Payment integration is added in the next phase.</p></aside></div>}</main>;
}
