"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, Save, Star } from "lucide-react";
import { AdminGuard } from "@/components/admin-guard";
import { supabase } from "@/lib/supabase/client";
import { formatCurrency } from "@/lib/utils";

type Product={id:string;slug:string;name:string;description:string;price:number;compare_at_price:number|null;category:string;image:string;badge:string|null;featured:boolean;stock_quantity:number;in_stock:boolean};
const empty:Omit<Product,"id">={slug:"",name:"",description:"",price:0,compare_at_price:null,category:"General",image:"",badge:null,featured:false,stock_quantity:0,in_stock:false};
export default function ProductsAdmin(){return <AdminGuard><Catalog/></AdminGuard>}
function Catalog(){const [items,setItems]=useState<Product[]>([]);const [draft,setDraft]=useState<Record<string,Partial<Product>>>({});const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 async function token(){if(!supabase)throw Error("Supabase is not configured.");const {data}=await supabase.auth.getSession();if(!data.session)throw Error("Admin session expired.");return data.session.access_token}
 async function load(){try{const r=await fetch('/api/admin/products',{headers:{Authorization:`Bearer ${await token()}`}});const j=await r.json();if(!r.ok)throw Error(j.error);setItems(j.products||[])}catch(e:any){setMessage(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function change(id:string,key:string,value:any){setDraft(d=>({...d,[id]:{...d[id],[key]:value}}))}
 async function save(id:string){try{const r=await fetch('/api/admin/products',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({id,...draft[id]})});const j=await r.json();if(!r.ok)throw Error(j.error);setItems(x=>x.map(p=>p.id===id?j.product:p));setDraft(d=>{const n={...d};delete n[id];return n});setMessage('Product saved successfully.')}catch(e:any){setMessage(e.message)}}
 async function create(){try{const r=await fetch('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify(empty)});const j=await r.json();if(!r.ok)throw Error(j.error);setItems(x=>[j.product,...x]);setMessage('Draft product created. Complete its fields and save.')}catch(e:any){setMessage(e.message)}}
 return <main className="container-shop py-10 sm:py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">ONECLICK control center</p><h1 className="mt-2 text-4xl font-black tracking-tight">Product catalogue</h1><p className="mt-3 text-neutral-500">Create, price, feature and manage live inventory from one place.</p></div><div className="flex gap-2"><Link href="/admin" className="btn-secondary"><ArrowLeft size={16}/> Dashboard</Link><button onClick={create} className="btn-primary"><Plus size={16}/> Add product</button></div></div>
 {message&&<div className="mt-6 rounded-2xl bg-white p-4 text-sm font-semibold shadow-soft">{message}</div>}
 {loading?<div className="py-20 text-center text-neutral-500">Loading catalogue…</div>:<div className="mt-8 space-y-5">{items.map(p=><div key={p.id} className="rounded-[30px] bg-white p-5 shadow-soft transition duration-500 hover:shadow-xl sm:p-7"><div className="grid gap-6 lg:grid-cols-[120px_1fr_auto] lg:items-start"><div className="aspect-square overflow-hidden rounded-2xl bg-neutral-100">{p.image&&<img src={p.image} alt="" className="h-full w-full object-cover"/>}</div><div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Name</span><input className="input-shop" value={draft[p.id]?.name??p.name} onChange={e=>change(p.id,'name',e.target.value)}/></label><label><span className="field-label">Slug (read only)</span><input className="input-shop bg-neutral-100" value={p.slug} readOnly/></label><label><span className="field-label">Category</span><input className="input-shop" value={draft[p.id]?.category??p.category} onChange={e=>change(p.id,'category',e.target.value)}/></label><label><span className="field-label">Price ₹</span><input className="input-shop" type="number" min="0" value={draft[p.id]?.price??p.price} onChange={e=>change(p.id,'price',Number(e.target.value))}/></label><label><span className="field-label">Compare price ₹</span><input className="input-shop" type="number" min="0" value={draft[p.id]?.compare_at_price??p.compare_at_price??''} onChange={e=>change(p.id,'compareAtPrice',e.target.value===''?'':Number(e.target.value))}/></label><label><span className="field-label">Stock</span><input className="input-shop" type="number" min="0" value={draft[p.id]?.stock_quantity??p.stock_quantity} onChange={e=>change(p.id,'stockQuantity',Number(e.target.value))}/></label><label><span className="field-label">Image URL</span><input className="input-shop" value={draft[p.id]?.image??p.image} onChange={e=>change(p.id,'image',e.target.value)}/></label><label className="sm:col-span-2"><span className="field-label">Description</span><textarea className="input-shop min-h-24" value={draft[p.id]?.description??p.description} onChange={e=>change(p.id,'description',e.target.value)}/></label><label className="flex items-center gap-3 rounded-2xl bg-[#f5f3ee] px-4 py-3 text-sm font-bold"><input type="checkbox" checked={draft[p.id]?.featured??p.featured} onChange={e=>change(p.id,'featured',e.target.checked)}/><Star size={15}/> Featured</label></div><button onClick={()=>save(p.id)} className="btn-primary"><Save size={16}/> Save</button></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-neutral-100 px-3 py-1.5">{p.in_stock?'Live':'Hidden / out of stock'}</span><span className="rounded-full bg-neutral-100 px-3 py-1.5">{formatCurrency(p.price)}</span><span className="rounded-full bg-neutral-100 px-3 py-1.5">{p.stock_quantity} units</span></div></div>)}</div>}
 </main>}
