import Link from "next/link";
import { ArrowRight, Check, ShieldCheck, Truck, RotateCcw } from "lucide-react";
import { products } from "@/data/products";
import { ProductCard } from "@/components/product-card";

export default function HomePage() {
  return <main>
    <section className="container-shop py-10 sm:py-16 lg:py-20"><div className="grid overflow-hidden rounded-[36px] bg-ink text-white lg:grid-cols-[1.05fr_.95fr]"><div className="flex flex-col justify-center p-8 sm:p-12 lg:p-16"><p className="eyebrow text-neutral-400">The everyday edit</p><h1 className="mt-5 max-w-2xl text-5xl font-black tracking-[-0.06em] sm:text-6xl lg:text-7xl">Better finds.<br/><span className="text-neutral-400">Less searching.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-neutral-300">Discover practical, beautiful products selected for modern life — without the endless scrolling.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="btn-primary bg-white text-black hover:bg-neutral-100">Shop the collection <ArrowRight size={17}/></Link><Link href="#featured" className="btn-secondary border-white/20 bg-transparent text-white hover:border-white">Explore featured</Link></div></div><div className="relative min-h-[390px] overflow-hidden lg:min-h-full"><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=85" alt="Modern retail collection" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/20"/><div className="absolute bottom-6 left-6 rounded-2xl bg-white/90 px-5 py-4 text-black backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-widest text-neutral-500">Curated weekly</p><p className="mt-1 text-sm font-bold">New drops, useful upgrades.</p></div></div></div></section>

    <section className="border-y border-black/5 bg-white"><div className="container-shop grid gap-6 py-6 sm:grid-cols-3"><div className="flex items-center gap-3"><Truck size={20}/><div><p className="text-sm font-bold">Reliable delivery</p><p className="text-xs text-neutral-500">Tracking on eligible orders</p></div></div><div className="flex items-center gap-3"><ShieldCheck size={20}/><div><p className="text-sm font-bold">Secure checkout</p><p className="text-xs text-neutral-500">Protected payments</p></div></div><div className="flex items-center gap-3"><RotateCcw size={20}/><div><p className="text-sm font-bold">Simple support</p><p className="text-xs text-neutral-500">Help when you need it</p></div></div></div></section>

    <section id="featured" className="container-shop py-20"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Handpicked</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Featured right now</h2></div><Link href="/shop" className="hidden items-center gap-2 text-sm font-bold sm:flex">View all <ArrowRight size={16}/></Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.filter(p => p.featured).slice(0,4).map(product => <ProductCard key={product.id} product={product}/>)}</div></section>

    <section className="container-shop pb-20"><div className="rounded-[32px] border border-black/10 bg-white p-8 sm:p-12"><div className="max-w-2xl"><p className="eyebrow">Why NEXORA</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A store designed around the things you actually need.</h2><p className="mt-4 leading-7 text-neutral-500">We focus on useful products, clear pricing and a calm buying experience. No clutter. No unnecessary noise.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{["Curated products", "Transparent pricing", "Mobile-first experience"].map(item => <div key={item} className="rounded-2xl bg-[#f7f4ee] p-5"><Check size={18}/><p className="mt-4 font-bold">{item}</p></div>)}</div></div></section>
  </main>;
}
